# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('lyric_path', models.CharField(max_length=200)),
                ('music_path', models.CharField(max_length=200)),
                ('frame_num', models.IntegerField(default=0)),
            ],
        ),
    ]
