# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_Info_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_local_id', models.IntegerField(default=0)),
                ('music_cloud_id', models.IntegerField(default=0)),
                ('music_title', models.CharField(max_length=100)),
                ('music_singer', models.CharField(max_length=100)),
                ('music_album', models.CharField(max_length=100)),
                ('lyric_path', models.CharField(max_length=200)),
                ('music_path', models.CharField(max_length=200)),
                ('album_cover_path', models.CharField(max_length=200)),
                ('music_type_label', models.CharField(max_length=200)),
                ('play_time', models.IntegerField(default=0)),
                ('frame_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
