# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170412_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_info_detail',
            name='album_cover_path',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='lyric_path',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_album',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_path',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_singer',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_title',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_type_label',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
