# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170412_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_info_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='album_cover_path',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='frame_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='lyric_path',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_local_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='music_path',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='music_info_detail',
            name='play_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
